CREATE TABLE IF NOT EXISTS USER (
  UserID    INTEGER PRIMARY KEY AUTOINCREMENT,
  Name      TEXT NOT NULL,
  Email     TEXT NOT NULL UNIQUE,
  Phone     TEXT,
  Department TEXT
);

CREATE TABLE IF NOT EXISTS ADMIN (
  AdminID       INTEGER PRIMARY KEY AUTOINCREMENT,
  Name          TEXT NOT NULL,
  ContactNumber TEXT
);

CREATE TABLE IF NOT EXISTS LOST_ITEM (
  LostItemID  INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName    TEXT NOT NULL,
  Category    TEXT,
  Description TEXT,
  DateLost    DATE NOT NULL,
  Is_Matched  INTEGER DEFAULT 0,
  UserID      INTEGER NOT NULL,
  FOREIGN KEY (UserID) REFERENCES USER(UserID)
);

CREATE TABLE IF NOT EXISTS FOUND_ITEM (
  FoundItemID INTEGER PRIMARY KEY AUTOINCREMENT,
  ItemName    TEXT NOT NULL,
  Category    TEXT,
  Description TEXT,
  DateFound   DATE NOT NULL,
  Is_Matched  INTEGER DEFAULT 0,
  AdminID     INTEGER NOT NULL,
  FOREIGN KEY (AdminID) REFERENCES ADMIN(AdminID)
);

CREATE TABLE IF NOT EXISTS MATCHES_WITH (
  LostItemID  INTEGER NOT NULL,
  FoundItemID INTEGER NOT NULL,
  PRIMARY KEY (LostItemID, FoundItemID),
  FOREIGN KEY (LostItemID)  REFERENCES LOST_ITEM(LostItemID),
  FOREIGN KEY (FoundItemID) REFERENCES FOUND_ITEM(FoundItemID)
);

CREATE TABLE IF NOT EXISTS CLAIM (
  ClaimID     INTEGER PRIMARY KEY AUTOINCREMENT,
  ClaimDate   DATE NOT NULL,
  Status      TEXT CHECK(Status IN ('Pending', 'Verified', 'Rejected')) DEFAULT 'Pending',
  UserID      INTEGER NOT NULL,
  FoundItemID INTEGER NOT NULL,
  AdminID     INTEGER,
  FOREIGN KEY (UserID)      REFERENCES USER(UserID),
  FOREIGN KEY (FoundItemID) REFERENCES FOUND_ITEM(FoundItemID),
  FOREIGN KEY (AdminID)     REFERENCES ADMIN(AdminID)
);
